admin:
  allow-send-email: ''
  allow-user-auth: ''
  redis:
    enabled: ''
  token: ''
auth:
  otp.max.retry: ''
cache:
  ttl:
    otp: ''
    resume-roast: ''
crypto:
  common-key: ''
  secret-token-key: ''
db:
  aurora:
    cluster:
      endpoint: ''
      region: ''
logging:
  level:
    com.bifrost.demo: ''
    io.lettuce.core: ''
    org.springframework.data.redis: ''
    remote.debug: ''
monitoring:
  cloudwatch:
    group-name: ''
    region: ''
    stream-name: ''
network:
  api:
    key:
      google-gemini: ''
parameter:
  encryption-rules: ''
  user-token-rules: ''
spring:
  data:
    redis:
      host: ''
      port: ''
      ssl:
        enabled: ''
  mail:
    host: ''
    password: ''
    port: ''
    properties:
      mail.smtp.auth: ''
      mail.smtp.starttls.enable: ''
    username: ''
  servlet:
    multipart:
      max-file-size: ''
      max-request-size: ''
springdoc:
  paths-to-exclude: ''